#ch11
#1 
install.packages("MASS")
library(MASS)
data(Animals)
head(Animals)
braincol<-Animals$brain
summary(braincol)
mean(braincol)
median(braincol)
sd(braincol)
max(braincol)
min(braincol)

#2 
  #조건1
data<-read.csv(file="descriptive.csv")
str(data)
type<-data$type
pass<-data$pass
table_type<-table(type)
table_pass<-table(pass)
barplot(table_type)
pie(table_type)


#조건2
install.packages("moments")
library(moments)
age<-data$age
age
summary(age)
mean(age)
sd(age)
skewness(age)
kurtosis(age)
x<-seq(35,80,0.1)
x
hist(age,freq=F)
lines(density(age))
curve(dnorm(x,mean(age),sd(age)),col='red',add=T)
